### ISSUE TITLE
Doesn't work anymore with Nuxt 2

### ISSUE THREAD

**Issue by davision** [davidroyer/nuxt-markdown-example#2]
I am using your example for I while iand it worked great. But now it broke with Nuxt 2. When using your example, the rendered html includes symbols like: `{ "default": "` and `\n`. Also images are therefor not shown, because the code is rendered like this: `<img src="\&quot;/image.jpg\&quot;" alt="\&quot;\&quot;">` Do you have a solution, how to fix this?

**Comment by elliotBraem** [comment]
Did you find a solution for this?

**Comment by davision** [comment]
Hey, yes I did actually. I've had to just add `.default` to content property. So for example, with Nuxt 2 you need to specify that default object: 

```html
<div v-html="$md.render(content.default)" />
```

In the previous version that wasn't required. The issue can be closed.

**Comment by DependencyHell** [comment]
Thanks for this, also to use _$md_ we need to add in _nuxt.config.js_ :

```
markdownit: {
    injected: true
}
```

**Comment by davision** [comment]
Yes, that's right! Forgot to mention.
